name: Run Fossa Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - uses: fossas/fossa-action@v1.1.0
        with:
          api-key: ${{ secrets.FOSSA_PUSH }}
