name: Run Fossa Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_PUSH }}
