name: 'build-test'
on:
  pull_request_target:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Test PR
          pr_source: test/pr
          pr_body: ${{ env.DATE }}
